version: 0.0
Resources:
  - testCodeDeploy:
      Type: AWS::Lambda::Function
      Properties:
        Name: "testCodeDeploy"
        Alias: "qa"
        CurrentVersion: "1"
        TargetVersion: "2"
Hooks:
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
