version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Serverless....
      - npm install -g serverless@1.61.2

  pre_build:
    commands:
      - cd backend
      - npm install

  build:
    commands:
      - sls deploy -s dev
