version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Serverless....
      - npm install -g serverless@1.80.0

  pre_build:
    commands:
      - cd backend
      - npm install

  build:
    commands:
      - sls deploy --alias local1
      - sls deploy --alias local2
