version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Serverless...
      - npm install -g serverless@1.80.0

  pre-build:
    commands:
      - cd backend
      - npm i
      - cd ../frontend
      - npm i

  build:
    commands:
      - npm run build
