service: backend-testtt

plugins:
  - serverless-offline
  - serverless-aws-alias

provider:
  name: aws
  runtime: nodejs12.x
  stage: local
  region: ap-southeast-2

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true
