service: backend

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: local
  region: us-east-2

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: get
          cors: true
